# Generated by Django 4.0.2 on 2022-02-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QandA',
            new_name='QuestionAnswer',
        ),
    ]
