# Generated by Django 4.0.2 on 2022-02-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='encoding',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
